name: antaranter_driverapp
description: A new Flutter project.

version: 1.0.5+5

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  avatars: ^3.0.2
  cached_network_image: 3.2.0
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  device_info: ^2.0.1
  dotted_border: ^2.0.0+1
  dropdown_search: ^2.0.1
  easy_mask: ^2.0.1
  encrypt: ^5.0.0
  expandable: ^5.0.1
  firebase_analytics: ^9.0.4
  firebase_core: ^1.13.1
  firebase_crashlytics: ^2.4.4
  firebase_dynamic_links: ^4.0.3
  firebase_messaging: ^11.2.11
  flutter_custom_clippers: ^2.0.0
  flutter_holo_date_picker: ^1.0.0-nullsafety.4
  flutter_html: ^2.1.2
  flutter_jailbreak_detection: ^1.8.0
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.1.4
  flutter_screenutil: ^5.0.1
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.23.0+1
  flutter_pdfview: ^1.2.1
  gallery_saver: ^2.3.2
  get: ^4.3.8
  get_it: ^7.2.0
  get_storage: ^2.0.2
  http: ^0.13.3
  http_parser: ^4.0.0
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.4+3
  intl: ^0.17.0
  jaguar_jwt: ^3.0.0
  jwt_decoder: ^2.0.1
  loading_overlay: ^0.3.0
  loading_animation_widget: ^1.1.0+1
  local_auth: ^1.1.8
  lottie: ^1.2.1
  mask_text_input_formatter: ^2.2.0
  package_info: ^2.0.2
  path_provider: ^2.0.5
  permission_handler: ^8.3.0
  pin_code_fields: ^7.3.0
  pinput: ^1.2.1
  pull_to_refresh: ^2.0.0
  scan: ^1.4.3
  screenshot: ^1.2.3
  share: ^2.0.4
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.12
  

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/icons/
    - assets/lottie/
  
  fonts: 
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf



